name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython kivy kivymd pillow requests beautifulsoup4 markdownify magika charset-normalizer defusedxml

    - name: Accept Android SDK licenses
      run: |
        mkdir -p ~/.android
        echo "count=0" > ~/.android/repositories.cfg
        sleep 10
        yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses || true

    - name: Install Android build tools
      run: |
        $ANDROID_SDK_ROOT/tools/bin/sdkmanager "build-tools;33.0.2" --sdk_root=$ANDROID_SDK_ROOT
        yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses

    - name: Install MarkItDown
      run: |
        cd packages/markitdown
        pip install -e .[all]
        cd ../..

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: markitdown-android-apk
        path: bin/*.apk
